name: krishibondhu
description: A Flutter app for farmers and agricultural community
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  image_picker: ^1.1.1
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  url_launcher: ^6.3.2
  intl: ^0.19.0
  
  # Firebase dependencies
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/