import 'package:cloud_firestore/cloud_firestore.dart';

class FirebaseDataUploader {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Upload all market prices data at once (40+ crops)
  Future<void> uploadMarketPricesData() async {
    try {
      // Complete data - সব বাংলায়, ৪০+ ফসল
      final List<Map<String, dynamic>> marketPrices = [
        // ========== সবজি (Vegetables) - ১৫টি ==========
        {
          'cropName': 'আলু',
          'category': 'সবজি',
          'price': 25.50,
          'unit': 'কেজি',
          'imageUrl': '🥔',
          'previousPrice': 23.00,
          'minPrice': 22.00,
          'maxPrice': 28.00,
          'avgPrice': 25.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'টমেটো',
          'category': 'সবজি',
          'price': 60.00,
          'unit': 'কেজি',
          'imageUrl': '🍅',
          'previousPrice': 65.00,
          'minPrice': 55.00,
          'maxPrice': 70.00,
          'avgPrice': 62.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'পেঁয়াজ',
          'category': 'সবজি',
          'price': 45.00,
          'unit': 'কেজি',
          'imageUrl': '🧅',
          'previousPrice': 42.00,
          'minPrice': 40.00,
          'maxPrice': 50.00,
          'avgPrice': 45.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'বেগুন',
          'category': 'সবজি',
          'price': 35.00,
          'unit': 'কেজি',
          'imageUrl': '🍆',
          'previousPrice': 32.00,
          'minPrice': 30.00,
          'maxPrice': 40.00,
          'avgPrice': 35.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'মরিচ',
          'category': 'সবজি',
          'price': 80.00,
          'unit': 'কেজি',
          'imageUrl': '🌶️',
          'previousPrice': 75.00,
          'minPrice': 70.00,
          'maxPrice': 90.00,
          'avgPrice': 80.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'গাজর',
          'category': 'সবজি',
          'price': 40.00,
          'unit': 'কেজি',
          'imageUrl': '🥕',
          'previousPrice': 38.00,
          'minPrice': 35.00,
          'maxPrice': 45.00,
          'avgPrice': 40.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'শসা',
          'category': 'সবজি',
          'price': 30.00,
          'unit': 'কেজি',
          'imageUrl': '🥒',
          'previousPrice': 28.00,
          'minPrice': 25.00,
          'maxPrice': 35.00,
          'avgPrice': 30.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'লাউ',
          'category': 'সবজি',
          'price': 20.00,
          'unit': 'কেজি',
          'imageUrl': '🥬',
          'previousPrice': 18.00,
          'minPrice': 15.00,
          'maxPrice': 25.00,
          'avgPrice': 20.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'ফুলকপি',
          'category': 'সবজি',
          'price': 50.00,
          'unit': 'কেজি',
          'imageUrl': '🥦',
          'previousPrice': 48.00,
          'minPrice': 45.00,
          'maxPrice': 55.00,
          'avgPrice': 50.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'বাঁধাকপি',
          'category': 'সবজি',
          'price': 35.00,
          'unit': 'কেজি',
          'imageUrl': '🥬',
          'previousPrice': 33.00,
          'minPrice': 30.00,
          'maxPrice': 40.00,
          'avgPrice': 35.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'শিম',
          'category': 'সবজি',
          'price': 55.00,
          'unit': 'কেজি',
          'imageUrl': '🫛',
          'previousPrice': 52.00,
          'minPrice': 50.00,
          'maxPrice': 60.00,
          'avgPrice': 55.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'পটল',
          'category': 'সবজি',
          'price': 45.00,
          'unit': 'কেজি',
          'imageUrl': '🥒',
          'previousPrice': 42.00,
          'minPrice': 40.00,
          'maxPrice': 50.00,
          'avgPrice': 45.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'করলা',
          'category': 'সবজি',
          'price': 38.00,
          'unit': 'কেজি',
          'imageUrl': '🥒',
          'previousPrice': 35.00,
          'minPrice': 32.00,
          'maxPrice': 42.00,
          'avgPrice': 37.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'ঢেঁড়স',
          'category': 'সবজি',
          'price': 48.00,
          'unit': 'কেজি',
          'imageUrl': '🌱',
          'previousPrice': 45.00,
          'minPrice': 42.00,
          'maxPrice': 52.00,
          'avgPrice': 47.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'পালং শাক',
          'category': 'সবজি',
          'price': 25.00,
          'unit': 'কেজি',
          'imageUrl': '🥬',
          'previousPrice': 22.00,
          'minPrice': 20.00,
          'maxPrice': 28.00,
          'avgPrice': 24.00,
          'date': Timestamp.now(),
        },

        // ========== ফল (Fruits) - ১০টি ==========
        {
          'cropName': 'আম',
          'category': 'ফল',
          'price': 120.00,
          'unit': 'কেজি',
          'imageUrl': '🥭',
          'previousPrice': 115.00,
          'minPrice': 100.00,
          'maxPrice': 140.00,
          'avgPrice': 120.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'কলা',
          'category': 'ফল',
          'price': 50.00,
          'unit': 'ডজন',
          'imageUrl': '🍌',
          'previousPrice': 48.00,
          'minPrice': 45.00,
          'maxPrice': 55.00,
          'avgPrice': 50.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'পেঁপে',
          'category': 'ফল',
          'price': 35.00,
          'unit': 'কেজি',
          'imageUrl': '🍈',
          'previousPrice': 32.00,
          'minPrice': 30.00,
          'maxPrice': 40.00,
          'avgPrice': 35.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'আনারস',
          'category': 'ফল',
          'price': 80.00,
          'unit': 'পিস',
          'imageUrl': '🍍',
          'previousPrice': 75.00,
          'minPrice': 70.00,
          'maxPrice': 90.00,
          'avgPrice': 80.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'আপেল',
          'category': 'ফল',
          'price': 180.00,
          'unit': 'কেজি',
          'imageUrl': '🍎',
          'previousPrice': 175.00,
          'minPrice': 160.00,
          'maxPrice': 200.00,
          'avgPrice': 180.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'কমলা',
          'category': 'ফল',
          'price': 100.00,
          'unit': 'কেজি',
          'imageUrl': '🍊',
          'previousPrice': 95.00,
          'minPrice': 90.00,
          'maxPrice': 110.00,
          'avgPrice': 100.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'আঙুর',
          'category': 'ফল',
          'price': 250.00,
          'unit': 'কেজি',
          'imageUrl': '🍇',
          'previousPrice': 240.00,
          'minPrice': 230.00,
          'maxPrice': 270.00,
          'avgPrice': 250.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'তরমুজ',
          'category': 'ফল',
          'price': 30.00,
          'unit': 'কেজি',
          'imageUrl': '🍉',
          'previousPrice': 28.00,
          'minPrice': 25.00,
          'maxPrice': 35.00,
          'avgPrice': 30.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'লিচু',
          'category': 'ফল',
          'price': 150.00,
          'unit': 'কেজি',
          'imageUrl': '🍒',
          'previousPrice': 145.00,
          'minPrice': 140.00,
          'maxPrice': 160.00,
          'avgPrice': 150.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'পেয়ারা',
          'category': 'ফল',
          'price': 40.00,
          'unit': 'কেজি',
          'imageUrl': '🍐',
          'previousPrice': 38.00,
          'minPrice': 35.00,
          'maxPrice': 45.00,
          'avgPrice': 40.00,
          'date': Timestamp.now(),
        },

        // ========== শস্য (Grains) - ৫টি ==========
        {
          'cropName': 'ধান (BR-28)',
          'category': 'শস্য',
          'price': 55.00,
          'unit': 'কেজি',
          'imageUrl': '🌾',
          'previousPrice': 52.00,
          'minPrice': 50.00,
          'maxPrice': 58.00,
          'avgPrice': 54.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'গম',
          'category': 'শস্য',
          'price': 45.00,
          'unit': 'কেজি',
          'imageUrl': '🌾',
          'previousPrice': 42.00,
          'minPrice': 40.00,
          'maxPrice': 48.00,
          'avgPrice': 44.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'ভুট্টা',
          'category': 'শস্য',
          'price': 38.00,
          'unit': 'কেজি',
          'imageUrl': '🌽',
          'previousPrice': 35.00,
          'minPrice': 32.00,
          'maxPrice': 42.00,
          'avgPrice': 37.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'যব',
          'category': 'শস্য',
          'price': 42.00,
          'unit': 'কেজি',
          'imageUrl': '🌾',
          'previousPrice': 40.00,
          'minPrice': 38.00,
          'maxPrice': 45.00,
          'avgPrice': 42.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'জোয়ার',
          'category': 'শস্য',
          'price': 35.00,
          'unit': 'কেজি',
          'imageUrl': '🌾',
          'previousPrice': 32.00,
          'minPrice': 30.00,
          'maxPrice': 38.00,
          'avgPrice': 34.00,
          'date': Timestamp.now(),
        },

        // ========== ডাল (Pulses) - ৫টি ==========
        {
          'cropName': 'মসুর ডাল',
          'category': 'ডাল',
          'price': 110.00,
          'unit': 'কেজি',
          'imageUrl': '🫘',
          'previousPrice': 105.00,
          'minPrice': 100.00,
          'maxPrice': 120.00,
          'avgPrice': 110.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'মুগ ডাল',
          'category': 'ডাল',
          'price': 125.00,
          'unit': 'কেজি',
          'imageUrl': '🫘',
          'previousPrice': 120.00,
          'minPrice': 115.00,
          'maxPrice': 135.00,
          'avgPrice': 125.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'ছোলা',
          'category': 'ডাল',
          'price': 95.00,
          'unit': 'কেজি',
          'imageUrl': '🫘',
          'previousPrice': 90.00,
          'minPrice': 85.00,
          'maxPrice': 105.00,
          'avgPrice': 95.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'মটর ডাল',
          'category': 'ডাল',
          'price': 88.00,
          'unit': 'কেজি',
          'imageUrl': '🫛',
          'previousPrice': 85.00,
          'minPrice': 80.00,
          'maxPrice': 95.00,
          'avgPrice': 88.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'অড়হর ডাল',
          'category': 'ডাল',
          'price': 115.00,
          'unit': 'কেজি',
          'imageUrl': '🫘',
          'previousPrice': 110.00,
          'minPrice': 105.00,
          'maxPrice': 125.00,
          'avgPrice': 115.00,
          'date': Timestamp.now(),
        },

        // ========== মসলা (Spices) - ৫টি ==========
        {
          'cropName': 'রসুন',
          'category': 'মসলা',
          'price': 180.00,
          'unit': 'কেজি',
          'imageUrl': '🧄',
          'previousPrice': 175.00,
          'minPrice': 160.00,
          'maxPrice': 200.00,
          'avgPrice': 180.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'আদা',
          'category': 'মসলা',
          'price': 200.00,
          'unit': 'কেজি',
          'imageUrl': '🫚',
          'previousPrice': 190.00,
          'minPrice': 180.00,
          'maxPrice': 220.00,
          'avgPrice': 200.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'হলুদ',
          'category': 'মসলা',
          'price': 250.00,
          'unit': 'কেজি',
          'imageUrl': '🟡',
          'previousPrice': 240.00,
          'minPrice': 230.00,
          'maxPrice': 270.00,
          'avgPrice': 250.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'ধনিয়া',
          'category': 'মসলা',
          'price': 150.00,
          'unit': 'কেজি',
          'imageUrl': '🌿',
          'previousPrice': 145.00,
          'minPrice': 140.00,
          'maxPrice': 160.00,
          'avgPrice': 150.00,
          'date': Timestamp.now(),
        },
        {
          'cropName': 'জিরা',
          'category': 'মসলা',
          'price': 600.00,
          'unit': 'কেজি',
          'imageUrl': '🌰',
          'previousPrice': 580.00,
          'minPrice': 550.00,
          'maxPrice': 650.00,
          'avgPrice': 600.00,
          'date': Timestamp.now(),
        },
      ];

      // Upload data using batch (efficient way)
      final batch = _firestore.batch();

      for (var priceData in marketPrices) {
        final docRef = _firestore.collection('market_prices').doc();
        batch.set(docRef, priceData);
      }

      // Commit all at once
      await batch.commit();

      print('✅ Successfully uploaded ${marketPrices.length} market prices!');
    } catch (e) {
      print('❌ Error uploading data: $e');
      rethrow;
    }
  }

  /// Clear all existing data (use carefully!)
  Future<void> clearAllMarketPrices() async {
    final snapshot = await _firestore.collection('market_prices').get();
    final batch = _firestore.batch();

    for (var doc in snapshot.docs) {
      batch.delete(doc.reference);
    }

    await batch.commit();
    print('🗑️ All market prices cleared!');
  }
}
